name: Build and Upload Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cx_Freeze PyQt6 winshell darkdetect pywin32

    - name: Build the project
      run: |
        python setup.py build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: HeadsetControl-Qt-win
        path: build/HeadsetControl-Qt/
