name: Build

on:
  push:
    branches:
      - linux 

jobs:
  linux-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.4.2'
          host: 'linux'
          add-tools-to-path: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgl1-mesa-dev

      - name: Build with qmake
        run: |
          mkdir build
          cd build
          qmake ../HeadsetControl-Qt.pro CONFIG+=release
          make -j$(nproc)
          pwd
          ls
          chmod +x ./HeadsetControl-Qt

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: HeadsetControl-Qt_linux_64
          path: build/HeadsetControl-Qt