name: Release
on:
  workflow_dispatch:
    inputs:
      workflow_run_id:
        description: 'Build workflow run ID (optional - will use latest successful run if not provided)'
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Windows artifact
        uses: dawidd6/action-download-artifact@v9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          workflow_conclusion: success
          name: HeadsetControl-Qt_msvc_64
          run_id: ${{ inputs.workflow_run_id }}
          if_no_artifact_found: fail

      - name: Download Linux artifact
        uses: dawidd6/action-download-artifact@v9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          workflow_conclusion: success
          name: HeadsetControl-Qt_linux_64
          run_id: ${{ inputs.workflow_run_id }}
          if_no_artifact_found: fail

      - name: Get version from CMake
        id: cmake_version
        run: |
          VERSION=$(grep -oP 'project\([^)]*VERSION\s+\K[0-9]+\.[0-9]+\.[0-9]+' CMakeLists.txt)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Found version: $VERSION"

      - name: Create release and tag
        run: |
          VERSION="${{ steps.cmake_version.outputs.version }}"
          echo "Creating release for version: $VERSION"
          
          git tag $VERSION
          git push origin $VERSION
          echo "new_tag=$VERSION" >> $GITHUB_ENV

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.new_tag }}
          release_name: ${{ env.new_tag }}
          body: ""
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: HeadsetControl-Qt_msvc_64.zip
          asset_name: HeadsetControl-Qt_msvc_64.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: HeadsetControl-Qt_linux_64.zip
          asset_name: HeadsetControl-Qt_linux_64.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}